config/routes.rb
Rails.application.routes.draw do
  resources :railway_stations
  resources :trains
  resources :routes

  get 'welcome/index'
  root 'welcome#index'

end

app/models/railway_station.rb
class RailwayStation < ActiveRecord::Base
  validates :title, presence: true

  has_many :trains
  has_many :railway_stations_routes
  has_many :routes, through: :railway_stations_routes
end

app/models/railway_stations_route.rb
class RailwayStationsRoute < ActiveRecord::Base
  belongs_to :railway_station
  belongs_to :route
end

app/models/route.rb
class Route < ActiveRecord::Base
  has_many :railway_stations_routes
  has_many :railway_stations, through: :railway_stations_routes

  validates :name, presence: true
end

app/models/train.rb
class Train < ActiveRecord::Base
  validates :number, presence:  true

  belongs_to :current_station, class_name: 'RailwayStation', foreign_key:  :current_station_id
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/railway_stations_controller.rb
class RailwayStationsController < ApplicationController
  before_action :set_railway_station, only: [:show, :edit, :update, :destroy]

  # GET /railway_stations
  # GET /railway_stations.json
  def index
    @railway_stations = RailwayStation.all
  end

  # GET /railway_stations/1
  # GET /railway_stations/1.json
  def show
  end

  # GET /railway_stations/new
  def new
    @railway_station = RailwayStation.new
  end

  # GET /railway_stations/1/edit
  def edit
  end

  # POST /railway_stations
  # POST /railway_stations.json
  def create
    @railway_station = RailwayStation.new(railway_station_params)

    respond_to do |format|
      if @railway_station.save
        format.html { redirect_to @railway_station, notice: 'Railway station was successfully created.' }
        format.json { render :show, status: :created, location: @railway_station }
      else
        format.html { render :new }
        format.json { render json: @railway_station.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /railway_stations/1
  # PATCH/PUT /railway_stations/1.json
  def update
    respond_to do |format|
      if @railway_station.update(railway_station_params)
        format.html { redirect_to @railway_station, notice: 'Railway station was successfully updated.' }
        format.json { render :show, status: :ok, location: @railway_station }
      else
        format.html { render :edit }
        format.json { render json: @railway_station.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /railway_stations/1
  # DELETE /railway_stations/1.json
  def destroy
    @railway_station.destroy
    respond_to do |format|
      format.html { redirect_to railway_stations_url, notice: 'Railway station was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_railway_station
      @railway_station = RailwayStation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def railway_station_params
      params.require(:railway_station).permit(:title)
    end
end

app/controllers/routes_controller.rb
class RoutesController < ApplicationController
  before_action :set_route, only: [:show, :edit, :destroy, :update]

  def index
    @routes = Route.all
  end

  def show
  end

  def new
    @route = Route.new
  end

  def create
    @route = Route.new(route_params)
    if @route.save
      redirect_to @route
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @route.update(route_params)
      redirect_to @route
    else
      render :edit
    end
  end

  def destroy
    @route.destroy
    redirect_to routes_path
  end

  private

  def set_route
    @route = Route.find(params[:id])
  end

  def route_params
    params.require(:route).permit(:name)
  end

end

app/controllers/trains_controller.rb
class TrainsController < ApplicationController
  before_action :set_train, only: [:show, :edit, :destroy, :update]
  def index
    @trains = Train.all
  end

  def show
  end

  def new
    @train = Train.new
  end

  def create
    @train = Train.new(train_params)
    if @train.save
      redirect_to @train
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @train.update(train_params)
      redirect_to @train
    else
      render :edit
    end
  end

  def destroy
    @train.destroy
    redirect_to trains_path
  end

  private

  def set_train
    @train = Train.find(params[:id])
  end

  def train_params
    params.require(:train).permit(:number, :current_station_id)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/railway_stations_helper.rb
module RailwayStationsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/common/_errors.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(resource.errors.count, "error") %> prohibited this railway_station from being saved:</h2>

    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Tutu</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/railway_stations/_form.html.erb
<%= form_for(@railway_station) do |f| %>

  <%= render 'common/errors', resource: @railway_station %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/railway_stations/edit.html.erb
<h1>Editing Railway Station</h1>

<%= render 'form' %>

<%= link_to 'Show', @railway_station %> |
<%= link_to 'Back', railway_stations_path %>

app/views/railway_stations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Railway Stations</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @railway_stations.each do |railway_station| %>
      <tr>
        <td><%= railway_station.title %></td>
        <td><%= link_to 'Show', railway_station %></td>
        <td><%= link_to 'Edit', edit_railway_station_path(railway_station) %></td>
        <td><%= link_to 'Destroy', railway_station, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Railway station', new_railway_station_path %>

app/views/railway_stations/new.html.erb
<h1>New Railway Station</h1>

<%= render 'form' %>

<%= link_to 'Back', railway_stations_path %>

app/views/railway_stations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @railway_station.title %>
</p>

<% if @railway_station.routes.empty? %>
  <p>Станция не входит ни в один маршрут</p>
<% else %>
  <p>Станция входит в следующие маршруты:</p>
  <ul>
    <% @railway_station.routes.each do |route| %>
      <li><%= route.name %></li>
    <% end %>
  </ul>
<% end %>

<%= link_to 'Edit', edit_railway_station_path(@railway_station) %> |
<%= link_to 'Back', railway_stations_path %>

app/views/routes/_form.html.erb
<%= form_for(@route) do |f| %>

  <%= render 'common/errors', resource: @route %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>

  <div class="actions">
    <%= f.submit "#{ @route.new_record? ? 'Create' : 'Edit'}" %>
  </div>
<% end %>

app/views/routes/edit.html.erb
<h1>Edit route</h1>

<%= render 'form' %>


<%= link_to 'Back', routes_path %>

app/views/routes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Routes</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
  <% @routes.each do |route| %>
    <tr>
      <td><%= route.name %></td>
      <td><%= link_to 'Show', route %></td>
      <td><%= link_to 'Edit', edit_route_path(route) %></td>
      <td><%= link_to 'Destroy', route, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Route', new_route_path %>

app/views/routes/new.html.erb
<h1>New route</h1>

<%= render 'form' %>


<%= link_to 'Back', routes_path %>

app/views/routes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @route.name %>
</p>

<%= link_to 'Edit', edit_route_path(@route) %> |
<%= link_to 'Back', routes_path %>

app/views/trains/_form.html.erb
<%= form_for(@train) do |f| %>

  <%= render 'common/errors', resource: @train %>

  <div class="field">
    <%= f.label :number %><br>
    <%= f.text_field :number %>
  </div>

  <div class="field">
    <%= f.label :current_station, "Current station:" %>
    <%= f.collection_select :current_station_id, RailwayStation.all, :id, :title %>
  </div>

  <div class="actions">
    <%= f.submit "#{ @train.new_record? ? 'Create' : 'Edit'}" %>
  </div>
<% end %>

app/views/trains/_train.html.erb
<tr>
  <td><%= train.number %></td>
  <td><%= link_to 'Show', train %></td>
  <td><%= link_to 'Edit', edit_train_path(train) %></td>
  <td><%= link_to 'Destroy', train, method: :delete, data: { confirm: 'Are you sure?' } %></td>
</tr>

app/views/trains/edit.html.erb
<h1>Edit train</h1>

<%= render 'form' %>


<%= link_to 'Back', trains_path %>

app/views/trains/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Trains</h1>

<table>
  <thead>
  <tr>
    <th>Number</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
<%= render @trains %>
  </tbody>
</table>

<br>

<%= link_to 'New train', new_train_path %>

app/views/trains/new.html.erb
<h1>New train</h1>

<%= render 'form' %>


<%= link_to 'Back', trains_path %>

app/views/trains/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Number:</strong>
  <%= @train.number %>
</p>
<p>
  <strong>Current station:</strong>
  <% if @train.current_station.present? %>
    <%= @train.current_station.title %>
  <% else %>
    Not enought
  <% end %>
</p>

<%= link_to 'Edit', edit_train_path(@train) %> |
<%= link_to 'Back', trains_path %>

app/views/welcome/index.html.erb
<h1>Hello Rails!</h1>
<%= link_to 'All stations', railway_stations_path %>